### ISSUE TITLE
Image not resizing

### ISSUE THREAD

**Issue by ozair-dev** [m-murad/compressor-head#20]
Hi, I am trying to resize an image but the api endpoint doesn't seem to work.
The example URL you've provided ```http://compressor-head.appspot.com/image```?image_url=```http://compressor-head.appspot.com/image```&width=500&height=350&format=jpeg is a little strange because it using the same url ```http://compressor-head.appspot.com/image``` fot both **api endpoint** and **image url**. Is there some issue with url formatting?
Can you provide me with a working example url so I can understand how it works?

**Comment by m-murad** [comment]
@ozair-dev 
the service is not working. You will have to deploy this using your google cloud. 

The image was hosted with the application, so both api and image url have same URL.
Please let me know if you need help deploying this
